# Used by Appstore-Sockets
name: Build-Test
on:
  workflow_call:
jobs:
  test-image-build:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set short git commit SHA
      id: vars
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

    - name: Confirm git commit SHA output
      run: echo ${{ steps.vars.outputs.short_sha }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: containers.renci.org
        username: ${{ secrets.CONTAINERHUB_USERNAME }}
        password: ${{ secrets.CONTAINERHUB_TOKEN }}
        logout: true

    - name: Parse Github Reference Name
      id: branch
      run: |
        REF=${{ github.ref_name }}
        echo "GHR=${REF%/*}" >> $GITHUB_OUTPUT
        

    # Notes on Cache: 
    # https://docs.docker.com/build/ci/github-actions/examples/#inline-cache
    - name: Build Container
      if: ${{ github.repository != 'helxplatform/appstore-sockets' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          containers.renci.org/${{ github.repository }}:test_${{ steps.branch.outputs.GHR }}
          ${{ github.repository }}:test_${{ steps.branch.outputs.GHR }}
        cache-from: type=registry,ref=${{ github.repository }}:buildcache
        cache-to: type=registry,ref=${{ github.repository }}:buildcache,mode=max

    - name: Build Server Container for Appstore-Sockets
      if: ${{ github.repository == 'helxplatform/appstore-sockets' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          containers.renci.org/${{ github.repository }}/server:test_${{ steps.branch.outputs.GHR }}
          ${{ github.repository }}/server:test_${{ steps.branch.outputs.GHR }}
        cache-from: type=registry,ref=${{ github.repository }}/server:buildcache
        cache-to: type=registry,ref=${{ github.repository }}/server:buildcache,mode=max

    - name: Build Monitor Container for Appstore-Sockets
      if: ${{ github.repository == 'helxplatform/appstore-sockets' }}
      uses: docker/build-push-action@v5
      with:
        context: ./monitoring
        file: ./monitoring/Dockerfile
        push: true
        tags: |
          containers.renci.org/${{ github.repository }}/monitor:test_${{ steps.branch.outputs.GHR }}
          ${{ github.repository }}/monitor:test_${{ steps.branch.outputs.GHR }}
        cache-from: type=registry,ref=${{ github.repository }}/monitor:buildcache
        cache-to: type=registry,ref=${{ github.repository }}/monitor:buildcache,mode=max
